/**
 * Docs content loader — reads MDX from `content/docs/`.
 *
 * Conventions:
 * - Filenames map to URL segments. `content/docs/get-started/cli.mdx`
 *   becomes `/docs/get-started/cli`. `index.mdx` is the section default
 *   (`content/docs/get-started/index.mdx` → `/docs/get-started`).
 * - Each file has YAML frontmatter:
 *     ---
 *     title: Quickstart — CLI
 *     description: One-line summary that appears in the sidebar tooltip.
 *     order: 1                # sort key within its parent section
 *     hidden: false           # default false; if true, file is loaded but
 *                             # not shown in the sidebar
 *     ---
 * - Headings (h2 / h3) on a page form the right-rail ToC.
 *
 * The whole tree is read at request time (or at build for SSG). Cheap —
 * docs content is small and cached aggressively by the Next.js renderer.
 */

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const DOCS_ROOT = path.join(process.cwd(), "content", "docs");

export interface DocFrontmatter {
  title: string;
  description?: string;
  order?: number;
  hidden?: boolean;
}

export interface DocPage {
  /** URL slug segments. `["get-started", "cli"]` for `/docs/get-started/cli`. */
  slug: string[];
  /** Filesystem path relative to `content/docs/`. */
  filePath: string;
  frontmatter: DocFrontmatter;
  /** Raw MDX body (with frontmatter stripped). */
  content: string;
}

export interface DocTreeNode {
  /** Slug segments leading to this node. */
  slug: string[];
  title: string;
  description?: string;
  order: number;
  hidden: boolean;
  /** True if this node has its own page (i.e., a corresponding mdx file).
   *  Section-only nodes that exist purely to group children are false. */
  hasPage: boolean;
  children: DocTreeNode[];
}

export interface DocHeading {
  /** Heading level (2 = h2, 3 = h3). h1 is the page title from frontmatter. */
  depth: 2 | 3;
  text: string;
  /** Slug for in-page anchor. Generated by rehype-slug. */
  id: string;
}

// ── Read a single page ───────────────────────────────────────

export function readDocPage(slug: string[]): DocPage | null {
  const candidates = candidatePaths(slug);
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      const raw = fs.readFileSync(candidate, "utf8");
      const { data, content } = matter(raw);
      return {
        slug,
        filePath: path.relative(DOCS_ROOT, candidate),
        frontmatter: normalizeFrontmatter(data, slug),
        content,
      };
    }
  }
  return null;
}

function candidatePaths(slug: string[]): string[] {
  if (slug.length === 0) {
    return [path.join(DOCS_ROOT, "index.mdx")];
  }
  const joined = path.join(DOCS_ROOT, ...slug);
  return [`${joined}.mdx`, path.join(joined, "index.mdx")];
}

function normalizeFrontmatter(data: Record<string, unknown>, slug: string[]): DocFrontmatter {
  return {
    title: typeof data.title === "string" ? data.title : titleCaseSlug(slug),
    description: typeof data.description === "string" ? data.description : undefined,
    order: typeof data.order === "number" ? data.order : 999,
    hidden: data.hidden === true,
  };
}

function titleCaseSlug(slug: string[]): string {
  if (slug.length === 0) return "Docs";
  const last = slug[slug.length - 1];
  return last
    .split("-")
    .map((s) => (s.length > 0 ? s[0].toUpperCase() + s.slice(1) : s))
    .join(" ");
}

// ── Build the navigation tree ────────────────────────────────

export function buildDocTree(): DocTreeNode {
  if (!fs.existsSync(DOCS_ROOT)) {
    return makeNode([], "Docs", 0);
  }
  const root = makeNode([], "Docs", 0);
  walk(DOCS_ROOT, [], root);
  sortTree(root);
  return root;
}

function makeNode(slug: string[], title: string, order: number): DocTreeNode {
  return {
    slug,
    title,
    order,
    hidden: false,
    hasPage: false,
    children: [],
  };
}

function walk(dir: string, slug: string[], node: DocTreeNode) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  // Two passes: subdirectories first (children sections), then mdx files
  // in this directory.
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const childSlug = [...slug, entry.name];
    const childNode = makeNode(childSlug, titleCaseSlug(childSlug), 999);
    walk(path.join(dir, entry.name), childSlug, childNode);
    node.children.push(childNode);
  }

  for (const entry of entries) {
    if (entry.isDirectory()) continue;
    if (!entry.name.endsWith(".mdx")) continue;

    const stem = entry.name.replace(/\.mdx$/, "");
    const raw = fs.readFileSync(path.join(dir, entry.name), "utf8");
    const fm = normalizeFrontmatter(matter(raw).data, slug);

    if (stem === "index") {
      // index.mdx is the section's own page — populate the parent node.
      node.title = fm.title;
      node.description = fm.description;
      node.order = fm.order ?? node.order;
      node.hidden = fm.hidden ?? false;
      node.hasPage = true;
      continue;
    }

    const childSlug = [...slug, stem];
    const existing = node.children.find((c) => c.slug.join("/") === childSlug.join("/"));
    if (existing) {
      // A directory and a same-named .mdx existed; treat the .mdx as the
      // section's own page.
      existing.title = fm.title;
      existing.description = fm.description;
      existing.order = fm.order ?? existing.order;
      existing.hidden = fm.hidden ?? false;
      existing.hasPage = true;
    } else {
      node.children.push({
        slug: childSlug,
        title: fm.title,
        description: fm.description,
        order: fm.order ?? 999,
        hidden: fm.hidden ?? false,
        hasPage: true,
        children: [],
      });
    }
  }
}

function sortTree(node: DocTreeNode) {
  node.children.sort((a, b) => {
    if (a.order !== b.order) return a.order - b.order;
    return a.title.localeCompare(b.title);
  });
  for (const child of node.children) sortTree(child);
}

// ── Extract headings for the right-rail ToC ──────────────────

const HEADING_RX = /^(#{2,3})\s+(.+?)\s*$/gm;

/**
 * Pull h2/h3 headings out of MDX source. Doesn't try to be perfect —
 * code-block contents are ignored via a simple fence-aware pass.
 */
export function extractHeadings(content: string): DocHeading[] {
  const headings: DocHeading[] = [];
  const stripped = stripCodeFences(content);

  HEADING_RX.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = HEADING_RX.exec(stripped)) !== null) {
    const depth = match[1].length === 2 ? 2 : 3;
    const text = match[2].trim().replace(/[*_`]/g, "");
    const id = slugifyHeading(text);
    headings.push({ depth, text, id });
  }
  return headings;
}

function stripCodeFences(content: string): string {
  return content.replace(/```[\s\S]*?```/g, "");
}

function slugifyHeading(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}
